apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: cilium-test
  name: cilium-test
spec:
  selector:
    matchLabels:
      app: cilium-test
  template:
    metadata:
      labels:
        app: cilium-test
    spec:
      containers:
      - image: reg.kubegg.io/library/nettool
        name: nettoolbox
        securityContext:
          privileged: true

---
apiVersion: v1
kind: Service
metadata:
  name: serversvc
spec:
  type: NodePort
  selector:
    app: cilium-test
  ports:
  - name: cni
    port: 80
    targetPort: 80
    nodePort: 32000
